### ISSUE TITLE
[feature]: autocomplete via LSP in the dap-repl

### ISSUE THREAD

**Issue by awwalker** [mfussenegger/nvim-dap#101]
I'm unsure if I'm just being ignorant or if this is actually a missing feature...

Right now in my setup when I launch a debugger and then attach using nvim-dap inside the dap-repl I cannot get the builtin LSP to trigger. Maybe there's something wrong in my setup or my completion trigger is being stepped on but this would be really nice to have if possible. Happy to help contribute if need be.

**Comment by mfussenegger** [comment]
nvim-dap already included a `omnifunc` implementation for the repl but there was an off-by-one error so sometimes you wouldn't get completion candidates. That's [now fixed](https://github.com/mfussenegger/nvim-dap/pull/102)


This doesn't use the LSP but rather the completion functionality provided by the debug adapter.

Using the LSP completion as a fallback would be difficult. The dap-repl is by default not attached to the LSP client because it has a different file type. I'm also not sure how the client and language servers would cope if the dap-repl buffer were attached. The server would then receive information about the repl contents and that is fairly different from the contents of regular source files. Best case it would not work, worst case it would cause the server to crash.


I've now also created a [PR](https://github.com/mfussenegger/nvim-dap/pull/103) that would add a small extension to trigger the completion automatically on trigger characters.

**Comment by awwalker** [comment]
Awesome! Thanks so much

**Comment by wookayin** [comment]
https://github.com/rcarriga/cmp-dap would be an alternative solution.
