### ISSUE TITLE
Feature request: reload config before showing config

### ISSUE THREAD

**Issue by mrdgo** [mfussenegger/nvim-dap#109]
I came across this 'issue' and thought this might affect others as well.

Basically I worked around my problem like this:

init.vim:
```vim
nmap <silent> <leader>ee <cmd>luafile $HOME/.config/nvim/lua/dap_python.lua<cr>
```

~/.config/nvim/lua/dap_python.lua:
```lua
dap.configurations.python = {
    {
        type = 'python';
        request = 'launch';
        name = 'Regular run';
        program = gps;
        args = {'pigps_cartpole'};
        console = dap.integratedTerminal;
        pythonPath = function()
            return gps_dir..'venv_gps/bin/python'
        end;
    },
    ...
```

It might be very useful to support this reloading natively. Maybe I specify a file for each filetype to be reloaded. Or the configurations have to be specified in `ftplugin/<lang>.vim` so you only reload that?

I didn't really think this through so it might be nonsense.
Please tell me, if this explanation of my idea is too fishy.

Kind regards,
Maxim

**Comment by mfussenegger** [comment]
Not sure if I understand the request correctly.

You'd like to make changes to your configuration file and then have nvim-dap pick up these changes?

If you load a module with `:lua require('...')` it gets cached and subsequent calls won't load it again. This is similar to a import statement in python.

What you can do is manually clear the cache. You could put something like the following into `~/.config/nvim/lua/my.lua`:


```lua
local M = {}
function M.reload(name)
  package.loaded[name] = nil
  return require(name)
end
return M
```

And then use `:lua require('my').reload('dap_python')` to clear the cache and reload it.
You could then change your mapping to always do the reload and trigger `dap.continue()` or something like that.


Doing this implicitly or having an explicit command within `nvim-dap` to reload the modules that modified `dap.configurations` would be difficult, because `nvim-dap` doesn't know that the module that made changes to `dap.configurations` is called `dap_python` (in your case). `nvim-dap` would have to track somehow which code modified the `dap.configurations` table and it would have to be able to re-run that. If the code that modified `dap.configurations` had other side effects that could also cause problems.

**Comment by mrdgo** [comment]
I like your solution very much!

Thank you Sir :)

Regarding your concern:

well I think this might be very easy. If `dap.configurations` isn't set directly but only the name of a module, you could simply load that module. I am not too familiar with Lua but maybe `dap.configurations` can be a table or a string. A string is interpreted as a module that can be reloaded and a table is static.

Feel free to close this issue if you are not convinced :)

**Comment by mfussenegger** [comment]
> well I think this might be very easy. If dap.configurations isn't set directly but only the name of a module, you could simply load that module. I am not too familiar with Lua but maybe dap.configurations can be a table or a string. A string is interpreted as a module that can be reloaded and a table is static.

That would limit how it can be extended and would conflict with how it can be used by some of the extensions.


> And it works like a charm! Maybe we can write something like this to the wiki? I think this might provide value to others as well :)

Yes makes sense. I think it would fit well into the [Cookbook](https://github.com/mfussenegger/nvim-dap/wiki/Cookbook) section. Do you want to extend it?

**Comment by mrdgo** [comment]
> > well I think this might be very easy. If dap.configurations isn't set directly but only the name of a module, you could simply load that module. I am not too familiar with Lua but maybe dap.configurations can be a table or a string. A string is interpreted as a module that can be reloaded and a table is static.
> 
> That would limit how it can be extended and would conflict with how it can be used by some of the extensions.
> 
> > And it works like a charm! Maybe we can write something like this to the wiki? I think this might provide value to others as well :)
> 
> Yes makes sense. I think it would fit well into the [Cookbook](https://github.com/mfussenegger/nvim-dap/wiki/Cookbook) section. Do you want to extend it?

Added it. Would you review it? If you are satisfied, close the issue :)

**Comment by theHamsta** [comment]
Isn't that way to complicated and specific? I mean you could also just do (reload on save)

`autocmd BufWritePost ~/your_magic_file :luafile %` 

or have a command to source current the current lua file (keymap for `:luafile %`). You would need that module reload thing only when you want to invalidate a whole range of modules not when you just want to set the value of table.

**Comment by mfussenegger** [comment]
> Added it. Would you review it?

Looked alright. 
I've also added the `:luafile` autocmd option as a second variant.

Closing this now
