### ISSUE TITLE
Don't move the cursor when advancing the debugger

### ISSUE THREAD

**Issue by haraldan** [mfussenegger/nvim-dap#1328]
### Problem Statement

Currently the cursor follows the debugger when it advances, moving to the start of currently stopped line. 

It would be great to be able to leave the cursor in place, for example, when using a hover window to evaluate a variable. Otherwise I have to navigate back to it every time.

If not everyone wants to have this behaviour by default, maybe it could be a config option?

**Comment by mfussenegger** [comment]
Can you elaborate a bit more on that?

If you don't want it to switch buffers or follow cursors you could set `:lua require("dap").defaults.fallback.switchbuf = ''` but I suspect that's not entirely what you want.

I find myself often placing the breakpoint below the variable I want to inspect and place the cursor already above the variable and then have it jump down. I think for a scenario like that I could introduce a new switchbuf options that prevents cursor jumps if the stopped location is already visible in a buffer and otherwise does nothing, that would allow something like `switchbuf = 'noop-if-visible,usetab,uselast'`

**Comment by haraldan** [comment]
The scenario I'm finding myself in is exactly as you describe. You're right, it would not make sense to not jump buffers if the breakpoint location is somewhere else. 
I would appreciate the option to leave the cursor in place when the breakpoint position is on screen, though.

**Comment by mfussenegger** [comment]
Could you try https://github.com/mfussenegger/nvim-dap/pull/1329 and see if that behaves as you'd expect?

**Comment by haraldan** [comment]
It works, thank you! And thanks for such a quick response.

I am thinking to also make an autocmd to update the variable values in the floating window automatically when the debugger advances. Do you think this would belong in the plugin, or should it remain separate?
