### ISSUE TITLE
GDB spams cli program

### ISSUE THREAD

**Issue by T0nd0Tara** [mfussenegger/nvim-dap#1345]
### Debug adapter definition and debug configuration

I have a cli program that i compiled with `gdb` symbols, and when I try to debug it with the following config, dap spams the enter key to go to the next line.
My cli program sees this new line as an empty command and does nothing. Is there a way to tell the gdb addapter to use the `c` key once, instead of spamming enters?

```lua
local dap = require("dap")
dap.adapters.gdb = {
  type = "executable",
  command = "gdb",
  args = { "--interpreter=dap", "--eval-command", "set print pretty on" }
}

dap.configurations.cpp = {
  {
    name = "Launch",
    type = "gdb",
    request = "launch",
    program = function()
      local build = vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
      dap.repl.open()
      return build
    end,
    cwd = "${workspaceFolder}",
    stopAtBeginningOfMainSubprogram = true,
    runInTerminal = true,
  },
}
```

### Steps to Reproduce

use the above config, with a cli app. and try to debug it

### Expected Result

it stops spamming enter, and let the user write something

### Actual Result

spams enter to continue execution

**Comment by mfussenegger** [comment]
I'm not sure what you mean with dap spaming enter. nvim-dap does no such thing.

gdb btw doesn't have a `runInTerminal` option. See https://sourceware.org/gdb/current/onlinedocs/gdb#Debugger-Adapter-Protocol for the supported configuration properties.

If you want to reduce the amount of text gdb shows in the dap-repl on start, you can provide the `-q` (quiet) option:

```lua
  dap.adapters.gdb = {
    type = "executable",
    command = "gdb",
    args = { "-q", "-i", "dap" }
  }
```

**Comment by T0nd0Tara** [comment]
when starting the debugger, I get this window, this is the REPL.
![image](https://github.com/user-attachments/assets/02cca7e7-25a8-4273-b851-ad673c9b7957)

the program wait for user input (as seen by the `>>`) and outputs the appropriate response

the `Token '', is not recognized` is when the user enters a non recognized input

i.e. the prompt
```
>> Hello world
```
would result in a `Token 'Hello', is not recognized` output

If I don't terminate Dap, it just continue forever.

**Comment by T0nd0Tara** [comment]
actually https://github.com/sakhnik/nvim-gdb works fine, I just didn't wanted to use that cause I like your plugin better.

So the client isn't the problem

**Comment by mfussenegger** [comment]
With client here in mean a debug-adapter-protocol client. 
nvim-gdb uses a different approach to communicate gdb. It is not using the debug adapter protcol.

With DAP, without `runInTerminal` support by the debug-adapter, the client only forwards the launch request to the debug-adapter and the debug-adapter then spawns the actual process. That means stdin handling is entirely up to it.

`runInTerminal` extends that. The client sends the launch request to the debug-adapter, the debug-adapter then tells the client to spawn some process in a terminal. The terminal is then controlled by the client and you can use stdin because nvim-dap uses the `:term` functionality.

So if you want to stick with nvim-dap your options are:

- Use another debug adapter like codelldb or cppdbg which support runInTerminal
- Add runInTerminal support to gdb
- Run the process in a terminal and then attach to it, instead of launching from it within neovim
- Refactor your app so you can have different entry points for debugging that don't need stdin. E.g. use test-cases.

**Comment by T0nd0Tara** [comment]
Thank you so much for the options. I will look into it
