### ISSUE TITLE
Hover moves the cursor on itself

### ISSUE THREAD

**Issue by Shatur** [mfussenegger/nvim-dap#161]
When I use `lua require("dap.ui.variables").hover()` my cursor moves inside the popup. Also, when I exit it, it does not disappear as it usually does with hover windows from LSP.

**Comment by mfussenegger** [comment]
This is kinda by design so that you can expand nested variables. To close the window you can use `CTRL-W_q`

**Comment by theHamsta** [comment]
The native LSP float is now also enterable (the bug preventing that seemed to be fixed). So `vim.lsp.util.open_floating_preview()` could also replace or optionally replace `popup` (except that buf and win are swapped).

**Comment by Shatur95** [comment]
Got it!
But how can I close or replace the window with another?

**Comment by theHamsta** [comment]
You could add an additional parameter to hover that creates the window and would use it when it's defined instead of popup https://github.com/theHamsta/nvim-dap/blob/724ea5aaa05dd7927d2745b7cf35a9f557e75c5c/lua/dap/ui/variables.lua#L275 . Additionally you would have to https://github.com/theHamsta/nvim-dap/blob/724ea5aaa05dd7927d2745b7cf35a9f557e75c5c/lua/dap/ui/variables.lua#L192-L213 to a separate function and apply it to the generated buffer. Or you let popup accept a window/buffer creation function

**Comment by mfussenegger** [comment]
@Shatur Did you have a look if the widget API covers your needs?

**Comment by Shatur** [comment]
@mfussenegger, hm... yes, I think this solves my issue.
