### ISSUE TITLE
missing debug symbols and a pile of usability questions

### ISSUE THREAD

**Issue by matu3ba** [mfussenegger/nvim-dap#239]
When I try to set breakpoints on a file with missing debug symbols, which can not be resolved (due to missing symbols), the plugin should exit.

Current behavior is to execute nevertheless, which creates a dangling program on an infinite loop.

A simplified approach would check existence of debug symbols and visualize a dialogue, if one wants to continue nevertheless.

An ideal solution would give a status icon with 1. optimization level + 2. debug symbols), so one can check before running.

**Comment by theHamsta** [comment]
Debugging will still make sense when you have debug symbols only for some parts of the code or when you debug a closed-source binary and see the asm of a failure case. Is there a easy way to check whether there are debug symbols? It could be warning that some of the breakpoints have been rejected.

**Comment by matu3ba** [comment]
> Is there a easy way to check whether there are debug symbols? It could be warning that some of the breakpoints have been rejected.

Sadly this issue still persists: https://github.com/microsoft/debug-adapter-protocol/issues/83, but I would expect that the debug adapter provides the response if the symbol for the debug point was found or not.
Do you have a test suite on the debug adapter stuff to ensure they work as expected or what do you rely on?
I am quite surprised you do not use the feedback from the debug adapter on setting breakpoints.

```
  symbolStatus?: string;

  /**
   * Logical full path to the symbol file. The exact definition is
   * implementation defined.
   */
  symbolFilePath?: string;
```
also indicates this taken from [section module in the spec](https://microsoft.github.io/debug-adapter-protocol/specification).

The more tricky part is how to communicate "future shared library loads" ie for preloading things from the linker or other more crazy things.
gdb has a separate command flag for ["future shared libraries"](https://stackoverflow.com/q/100444), so probably you could also do this as well.

**Comment by mfussenegger** [comment]
> When I try to set breakpoints on a file with missing debug symbols, which can not be resolved (due to missing symbols), the plugin should exit.

Currently it marks the breakpoint as rejected. You can see the breakpoint switching from `B` to `R`:

https://user-images.githubusercontent.com/38700/126814184-762df8dd-edb1-4441-81e6-edcc059abcd9.mp4

> Current behavior is to execute nevertheless, which creates a dangling program on an infinite loop.

Could you elaborate on the infinite loop? What do you see, steps to reproduce, etc.
Your inputs so far assume a lot of context that I'm missing. (Especially given that I hardly debug C or with other c-like languages with gdb)

**Comment by matu3ba** [comment]
> Currently it marks the breakpoint as rejected. You can see the breakpoint switching from B to R

This is my fault of not reading the manual until line 222, but to be fair you also do not mention this in the README and in the wiki.
For build systems, which can be super annoying (cmake), this is not a very good experience for new users.

There are some ideas I have for making this more simple to use:
1. change `R` to something more understandable => there is no consensus (default colors and cursors differentiate between tools)
2. a wiki entry that shows for various languages and build systems how to get debug symbols
3. vs code offers this integrated when one presses f5 (it does internally builds the binary with debug symbols), so maybe something simpler would also be possible in a plugin?
4. add the symbol meaning to the README
5. show use cases + how to use them (probably fits best in the wiki)

Step 2 would be kinda the pre-step to 3 and it would be very nice to have a collection of shell commands for various build systems.

> Could you elaborate on the infinite loop? What do you see, steps to reproduce, etc.

I have a broken test case that results in an infinite loop. I guess `quit` in gdb is in dap `stop`, but in the manual it is missing what happens to the running threads.
I do only see
```txt
stop()                                                              *dap.stop()*
        Closes the current session.
        To disconnect the adapter as well, call |dap.disconnect()| before
        calling |dap.stop()|
```

https://github.com/mfussenegger/nvim-dap#usage is missing how to gracefully stop debugging with `stop`. 
Some comparison sheet between gdb and lldb commands might be useful.

Sorry to bother you with another question:
```txt
pause({thread_id})                                                 *dap.pause()*
        Requests debug adapter to pause a thread. If there are multiple threads
        it stops `thread_id` from the optional parameter or asks the user which
        thread to pause.
```
pauses execution. Is it possible to print the program part which is executed next and setting a breakpoint? Does this belong into the REPL to not have exploding complexity?

**Comment by mfussenegger** [comment]
> change R to something more understandable => there is no consensus (default colors and cursors differentiate between tools)

Other IDEs/Debuggers use a crossed-out breakpoint. That's difficult to do in nvim-dap because it is not possible to put arbitrary icons into the signcolumn. It may be possible to find an emoji that fits - but there is the danger that not all fonts would include it, and then some users would have garbage characters displayed or nothing.

They also have tooltips on hover, - something that currently cannot be done within neovim as far as I'm aware.

I think `R` (or maybe `X`?) is a reasonable default.


> a wiki entry that shows for various languages and build systems how to get debug symbols


The wiki is open for edits by anyone. I think it would be great if you could make this addition.


> vs code offers this integrated when one presses f5 (it does internally builds the binary with debug symbols), so maybe something simpler would also be possible in a plugin?

The `dap.adapters` / `dap.configuration` system supports function evaluation which can be used to build the project. This was walked about in this issue https://github.com/mfussenegger/nvim-dap/issues/191

How a project is compiled is often build system specific and therefore doesn't fit into the nvim-dap core - which tries to stay agnostic of specific tooling.

But I think it would be great to extend the wiki with some common recipes. 


> add the symbol meaning to the README

I don't want to blow up the README too much - otherwise we run into the issue you mentioned initially in your comment ("Didn't read until...").

I could imagine that we create a "Troubleshooting" or "Common problems" section in the wiki and link to it within the readme.

It can then elaborate on missing debug symbols and what to do about it.

> https://github.com/mfussenegger/nvim-dap#usage is missing how to gracefully stop debugging with stop.

The usage section in the README is not meant as an exhaustive documentation. `:help dap.txt` is intended for that. If you find the documentation in `:help dap.txt` incomplete you could create a PR to improve it

> Some comparison sheet between gdb and lldb commands might be useful.

What does this have to do with nvim-dap?


> Is it possible to print the program part which is executed next and setting a breakpoint? Does this belong into the REPL to not have exploding complexity?


If you pause execution the thread will be stopped somewhere. You can jump to the location with the frames widget (or `.frames` within the REPL - then press `<CR>` if the cursor is over a frame).

**Comment by matu3ba** [comment]
> What does this have to do with nvim-dap?

I like tables that simplify stuff, but that is not necessary.

> The wiki is open for edits by anyone. I think it would be great if you could make this addition.

I will think of something and put it into the wiki.

Thanks a lot for the patience to answer all questions. I will put these things into the wiki and file a PR to clarify the help pages.

Everything answered, so I am closing this.

**Comment by matu3ba** [comment]
@mfussenegger I created https://github.com/mfussenegger/nvim-dap/wiki/Troubleshooting and https://github.com/mfussenegger/nvim-dap/wiki/Debug-symbols-in-various-languages-and-build-systems

I would suggest to create a discussion page with tag `wiki` for both xor keep a separate issue for both to discuss changes.
What do you think about that?

Sidenode: I did invoke UB by iterator invalidation in my c++ code, which resulted in an infinite loop.
Would you agree that 1. how to stop such programs belongs into the README and 2. how to quit ~~neovim~~ nvim-dap (the ´stop` command) ?

The manual changes will be discussed in the PR.

**Comment by mfussenegger** [comment]
> I would suggest to create a discussion page with tag wiki for both xor keep a separate issue for both to discuss changes.
What do you think about that?

I'd rather have a new discussion per concrete matter instead of having one generic meta issue.

> Sidenode: I did invoke UB by iterator invalidation in my c++ code, which resulted in an infinite loop.
Would you agree that 1. how to stop such programs belongs into the README and 2. how to quit neovim nvim-dap (the ´stop` command) ?


`disconnect` and `close` are already covered in the `dap-api` docs. I don't think we would improve the documentation by cluttering the readme with possible workflows.
