### ISSUE TITLE
Can it make any key to control terminal pane ?

### ISSUE THREAD

**Issue by hackingcat** [mfussenegger/nvim-dap#243]
### Problem Statement

In many cases, we want show or hide terminal pane just like repl pane.

### Ideas or possible solutions

Provide a lua api to toggle the terminal pane like `terminal.toggle`.

**Comment by mfussenegger** [comment]
This turns out to be a bit difficult due to the design of the `terminal_win_cmd`.

It can create a new buffer *and* a new window. So it is not really possible to add a `terminal.toggle` while preserving the `terminal_win_cmd` option. `nvim-dap` wouldn't know how to create *only* the new window, without also creating the buffer.


What you could do is create a custom function, for example, put the following in a `lua/mydapconfig.lua`:


```lua
local M = {}

M.terminal = require('dap.ui').new_view(
  function()
    return vim.api.nvim_buf_create(false, true)
  end,
  function(buf)
    vim.cmd('split')
    api.nvim_win_set
  end
)


require('dap').defaults.fallback.terminal_win_cmd = ':lua require("mydapconfig").terminal.open()

return M
```

With this you can then create a mapping to `:lua require('mydapconfig').terminal.toggle()<CR>`


(This requires https://github.com/mfussenegger/nvim-dap/pull/244)
