### ISSUE TITLE
exit() and toggle() functions

### ISSUE THREAD

**Issue by Shatur95** [mfussenegger/nvim-dap#31]
I see that some functions, such as `.up()`, `.stop()`, `.continue()` and other can be called from REPL and from lua directly.
But `.exit` function cannot be called from `lua`. Could you export it to Lua API? To have the ability to map something like `lua require'dap'.exit()` to a key.

Another suggestion is add `toggle()` function. Like in [Asyncrun](https://github.com/skywind3000/asyncrun.vim/blob/58d23e70569994b36208ed2a653f0a2d75c24fbc/plugin/asyncrun.vim#L1956). What do you think about it?

**Comment by mfussenegger** [comment]
Could you check https://github.com/mfussenegger/nvim-dap/pull/32 ?

I decided to only expose a `disconnect` method instead of `exit` - it behaves a bit different then `.exit` in the REPL and doesn't close the REPL automatically, you could still do that with:

`:lua require('dap').disconnect(); require('dap.repl').close()`

That should give a bit more flexibility.

**Comment by Shatur95** [comment]
Thank you!
Tested, works. But I noticed that `:require('dap.repl').close()` leaves REPL buffer (can be accessed by `:bnext`). Is it expected?

**Comment by mfussenegger** [comment]
> Tested, works. But I noticed that :require('dap.repl').close() leaves REPL buffer (can be accessed by :bnext). Is it expected?

I changed it to also delete the buffer and merged it. Thanks for testing it out.

**Comment by Shatur95** [comment]
Thank you!
