### ISSUE TITLE
Debugging breaks when multiple breakpoints are triggered

### ISSUE THREAD

**Issue by Abh15h3k** [mfussenegger/nvim-dap#575]
### Debug adapter definition and debug configuration

```
dap.adapters.java = function(callback)
    vim.lsp.buf_request(
        0,
        "workspace/executeCommand",
        { command = "vscode.java.startDebugSession" },
        function(err, res, _, _)
            if err then
                return
            end
            callback({ type = "server", host = "127.0.0.1", port = res })
        end
    )
end
```

configuration loaded via `require('dap.ext.vscode').load_launchjs()`

`.vscode/launch.json`
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Attach 5005",
            "request": "attach",
            "hostName": "localhost",
            "port": "5005"
        }
    ]
}
```

### Debug adapter version

java-debug 0.36.0

### Steps to Reproduce

In Spring Boot project with two GetMapping.

1. put breakpoints in both of the Mappings.
2. trigger first GetMapping using http(ie) or curl.
3. trigger second GetMapping using http(ie) or curl. 

https://user-images.githubusercontent.com/40197742/172163826-27ee56bc-1b19-4282-b8a1-11219b2de44d.mp4

### Expected Result

both Mapping are stopped on their breakpoints and we should be debugging the first Mapping breakpoint.
then after executing `require'dap'.continue()` start debugging the second breakpoint.

### Actual Result

execution does not stop at the second breakpoint. instead it continues. furthermore you loose the ability to "continue" the first breakpoint. must terminate session for the first breakpoint to continue.

**Comment by Abh15h3k** [comment]
resuming the thread works.

but going to the paused thread/frame doesn't give me stepping controls

**Comment by mfussenegger** [comment]
I think you only jumped to the location, but didn't resume. There is an action menu (keymap `a`) in the threads widget to resume a stopped thread.

I also created https://github.com/mfussenegger/nvim-dap/pull/580 which would overload `continue` further to prompt for the thread to resume. Could you give that a try?

I'm not sure yet about the behavior. Maybe it should be a dedicated menu option instead of showing an entirely different menu first.

I also considered marking one of the "background" stopped threads as the "main" thread automatically on continue, but that would have the side effect of potentially stepping interleaved/undeterministic between different threads. If I remember right that's how IntelliJ behaves and I always found that confusing. I usually want to follow the flow of a single thread.

**Comment by Abh15h3k** [comment]
I did resume through the `a` keymap menu. but if you notice the top right split. the API returned.

**Comment by mfussenegger** [comment]
I adjusted https://github.com/mfussenegger/nvim-dap/pull/580 slighty and merged it. `continue` will now show an option to select a thread to resume if it is not already "focused" on a paused thread.

**Comment by Abh15h3k** [comment]
i think there is some confusion. i want to be able to focus the paused thread and debug that thread. #580 just lets me unpause the thread.

**Comment by Abh15h3k** [comment]
https://user-images.githubusercontent.com/40197742/172769863-7153ba74-9f01-4434-9912-4e314bcad09d.mp4

**Comment by mfussenegger** [comment]
Can you check out https://github.com/mfussenegger/nvim-dap/pull/612 ? I think that should enable what you want to do.

**Comment by Abh15h3k** [comment]
sorry for the late response. i checked out the changes and seems to be working now.
Thanks!
