### ISSUE TITLE
Multi-Debug Session Support

### ISSUE THREAD

**Issue by inclyc** [mfussenegger/nvim-dap#586]
### Problem Statement

In VSCode, multiple debug sesssions can be launched at the same time. The benefit of this is to debug some languages that have FFI, such as C extensions for Python.

### Ideas or possible solutions

The current code seems to be written for a single debugger, we can assign a session number to each DAP, and then pass parameters in the debugger action (step over/into etc.) to determine which debug session to use. If there is currently only one DAP, just keep the legacy behaviour

**Comment by mfussenegger** [comment]
You could already create multiple sessions using the lower level APIs and switch around the active session using `set_session`. The bigger issue is that the breakpoints are global and use signs.

**Comment by mfussenegger** [comment]
I still want to improve this somehow but there are many details to consider. 

E.g if you set a breakpoint,  to which session does it go.  What if one session rejects it and another doesn't.
What if one session stops at a breakpoint while you're already stopped in another session.


There's also session hierarchy to consider for extensions like nvim-dap-python and nvim-dap-vscode-js

**Comment by johnybx** [comment]
now that the [reverse request StartDebugging](https://microsoft.github.io/debug-adapter-protocol/specification#Reverse_Requests_StartDebugging) is released do you plan to add support for multiple sessions @mfussenegger ?

**Comment by mfussenegger** [comment]
I plan to add support for `startDebugging`, but it's currently not implemented in any debug adapter.
And it's a bit different than what this issue is about - although related. `startDebugging` will use hierarchical sessions. This one is about having multiple top-level sessions.

**Comment by mxsdev** [comment]
@mfussenegger 

[According to this comment](https://github.com/microsoft/vscode-js-debug/issues/902#issuecomment-1304592234) support in `vscode-js-debug` will happen soon.

Just wanted to say that I'm very happy to help in the adoption of `startDebugging` due to its importance for `nvim-dap-vscode-js` 👍 

One concern, as you were mentioning earlier, is on the fact that breakpoints are currently handled globally, which poses a problem for hierarchical/multi-sessions. Looking at the codebase it seems this is still the case. I remember around the time you posted [this][ref1], I spent some time trying to solve the problem on the `nvim-dap` side, and it got pretty complicated and messy pretty quick, so I kind of gave up on it for the time being.

This is a good excuse to work on it though. Would you be open to a PR that reworked breakpoints to be per-session, assuming I can find a reasonable way to accomplish it?

[ref1]: https://github.com/mxsdev/nvim-dap-vscode-js/issues/1#issuecomment-1200106184

**Comment by mfussenegger** [comment]
>  Would you be open to a PR that reworked breakpoints to be per-session, assuming I can find a reasonable way to accomplish it?

Thanks for the offer, but I think I'll look into this myself once I get to implement `startDebugging`. It's also important for `debugpy` for multiprocessing support.

I suspect that reworking them to make them per-session may even be the wrong thing to do, because I it could be that _all_ sessions will need to receive the breakpoint info. It was unfortunately left unspecified in the specification. If that's the case there'll need to be some broadcast mechanism, and the rejection handling will need to account for one session rejecting and another session accepting.

**Comment by mfussenegger** [comment]
`startDebugging` is merged too (https://github.com/mfussenegger/nvim-dap/pull/853)
