### ISSUE TITLE
load_launchjs should use json5 for parsing

### ISSUE THREAD

**Issue by gutyina70** [mfussenegger/nvim-dap#650]
### Problem Statement

Currently a valid launch.json for vscode may not be valid for nvim-dap. For example load_launchjs throws errors when it encounters trailing commas or multiline comments.

### Ideas or possible solutions

Use a library like https://github.com/Joakker/lua-json5 for parsing launch.json instead of neovim's built in json_decode. Usually launch.json files are not too big, so performance shouldn't be an issue. This can also be an optional dependency and keep built in json_decode as a fallback for parsing.

**Comment by mfussenegger** [comment]
I'm not sure I want to pull in lua-json5 as (optional) dependency. It hasn't had a release and the author hasn't been very active in the last couple months, so I'm not sure how solid it is. Even if it is "only" json.

But I could imagine exposing the decode function so that people could override it.

E.g.

```lua
require('dap.ext.vscode').json_decode = json5.parse
```

**Comment by mwcz** [comment]
Exposing the decode function would be really nice.  I work on projects alongside mostly vscode users and it would feel nice to not put restrictions on their launch.json formatting and commenting.

**Comment by mwcz** [comment]
Thank you!
