### ISSUE TITLE
use case: record debugging steps and redo without the last "step" (having no rr workaround)

### ISSUE THREAD

**Issue by matu3ba** [mfussenegger/nvim-dap#725]
### Problem Statement

Without a backtrace (and thanks to poor dynamic linking without debug symbols or unwinding info etc), it can be very frustrating to pin down the origin of the fault (the bug) or even the origin of failure (segfault etc) by repeatedly stepping forwards from the initial program state due to complex/big input.

Ideally, one could use `rr`, which collects all necessary info and step backwards, but that is often not the case.

### Possible Solutions

Describe or offer a way how to record, edit and play all debugging steps by a user-defined starting point. This could work like `gdb -x COMMAND_FILE` with the `COMMAND_FILE` being a file written to after each user input, editable in a buffer and executed with the command to start the debug session.

Side question: Is it currently possible to adjust environment variables like `PATH` to be empty without breaking program execution or is this considered out of scope?

More advanced question: Is there an API to get variable names and states into a scratch buffer?

### Considered Alternatives

I will hack up something with gdb and harpoon, but I have no idea how to get the script info into nvim-dap.
Further, I strongly dislike the superfluous "gimme stack" keypresses and would rather have a way to properly see variables.

**Comment by mfussenegger** [comment]
I'm not sure how feasible this is due to program execution being potentially non-deterministic

Consider something like:

```
if randomint() == 2:
  foo()
else:
  bar()
```

If you record the steps and then repeat them, it may end up running into the different function, at which point nothing from the previous execution matches.

That said, you could try to write this as an extension and record the functions you call and the responses from the server via the extension points. See `:h dap-extensions`


>  Is it currently possible to adjust environment variables like PATH to be empty without breaking program execution or is this considered out of scope?

It's up to the debug adapter to support something like that. The client supports evaluate/setVariable requests


> Is there an API to get variable names and states into a scratch buffer?

You can use the `request` method of the `session` to make arbitrary requests.


> Further, I strongly dislike the superfluous "gimme stack" keypresses and would rather have a way to properly see variables.

Not sure what you mean with superfluous "gimme stack" keypresses?
There are built-in widgets to have a variables sidebar or you can use nvim-dap-ui.
