### ISSUE TITLE
Add command line arguments to show execute/debug

### ISSUE THREAD

**Issue by WindowHZT** [mfussenegger/nvim-dap#847]
### Problem Statement

Add command line arguments to show execute/debug when dap starts。Just like IDEA, display the executed command。

![Snipaste_2023-02-02_15-55-35](https://user-images.githubusercontent.com/78307930/216266396-8a733a29-6cda-4138-99b2-6553a171ad6d.png)

**Comment by mfussenegger** [comment]
nvim-dap doesn't have a reliable way to do that because in `console` mode the debug adapter itself spawns the debugee. nvim-dap won't know the executable or exact arguments used.

With the `integratedTerminal` or external terminal it would be possible, but not sure if having inconsistent behavior is desirable. It's also not clear where to show it (REPL, integrated terminal, elsewhere?)


I personally also wouldn't like it. (Because classpaths in Java are often huge, I don't need to see that long string)


What you could do is to create the message yourself. You could create a `launch` listener and then use the request payload:


```lua
dap.listeners.after.launch['show_launch'] = function(session, err, response, request)
  -- Use info from `request` - this will basically be the `dap-configuration` you used.
end
```
