### ISSUE TITLE
Would it be possible to update watches when a log breakpoint is hit?

### ISSUE THREAD

**Issue by joshpetit** [mfussenegger/nvim-dap#968]
### Problem Statement

For example, if I were to have a watch on a specific variable and then add a log break point right after the variable is manipulated, would it be possible to update the variable inside the watch?

I'm not sure if this is debugger specific, I have a feeling like it is though.

**Comment by mfussenegger** [comment]
nvim-dap core currently doesn't have watches? I'm not sure what you're referring to.

**Comment by joshpetit** [comment]
Yes, I see the watches, but they don't update until you stop at a break point. I was wondering if it'd be possible to update them every time we pass over a log breakpoint. In particular I just want to see the the variable update in a "live" kind of way in the watch

**Comment by rcarriga** [comment]
Currently as you said the watches refresh when a breakpoint is reached. From an implementation POV this happens when a `scopes` request happens because nvim-dap makes that request and there is some data processing that is required in nvim-dap-ui so it can't just listen for a `stopped` event. 

To make it refresh on other events, you can use the `client.listen`  to call `send_ready` which triggers a render. You can see the existing code here https://github.com/rcarriga/nvim-dap-ui/blob/c693e80f8d7b6369f4152e7fdab10db4847c5c71/lua/dapui/components/watches.lua#L13-L16
So something like this should be a good start
```lua
  client.listen.scopes(function()
    running = true
    send_ready()
  end)
  client.listen.output(send_ready)
```

If you have [neodev](https://github.com/folke/neodev.nvim) setup, you should see type hints, docs etc for the client to help use it
If you have any issues, feel free to open an issue on nvim-dap-ui (don't want to cause noise here :sweat_smile:)

**Comment by mfussenegger** [comment]
One thing to note is that given that log breakpoints don't stop, you don't have a frame for which you can resolve the scopes. And even if you had, by the time you made the request and got responses, the process very likely moved to a different state

**Comment by joshpetit** [comment]
Yeaa. That explains why when I tried resolving the scope it didn't update. I'll probably try making some way to break at a certain point and auto continue after resolving the scope. Thanks
